// File generated by FlutterFire CLI.
// For more info see https://firebase.google.com/docs/cli/flutter#generate-clients
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for different platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.');
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SHGzzl7MiOhdI0x7YPmvvU4fm4sGLIM',
    appId: '1:658701940288:android:cddd8dc57e2719d18c11a5',
    messagingSenderId: '658701940288',
    projectId: 'unieventosapp',
    storageBucket: 'unieventosapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2nOiFMWM2hs7PAFSTSMr0cLzEpg7sTI',
    appId: '1:658701940288:web:85a80ef91d6e375b8c11a5',
    messagingSenderId: '658701940288',
    projectId: 'unieventosapp',
    authDomain: 'unieventosapp.firebaseapp.com',
    storageBucket: 'unieventosapp.firebasestorage.app',
    measurementId: 'G-8SJ6EPY6Z1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntdh3qI9yzqj-ka49tjZo0N38yPdPxaA',
    appId: '1:658701940288:ios:87a4806bc862979c8c11a5',
    messagingSenderId: '658701940288',
    projectId: 'unieventosapp',
    storageBucket: 'unieventosapp.firebasestorage.app',
    iosBundleId: 'com.yourdomain.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntdh3qI9yzqj-ka49tjZo0N38yPdPxaA',
    appId: '1:658701940288:ios:87a4806bc862979c8c11a5',
    messagingSenderId: '658701940288',
    projectId: 'unieventosapp',
    storageBucket: 'unieventosapp.firebasestorage.app',
    iosBundleId: 'com.yourdomain.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2nOiFMWM2hs7PAFSTSMr0cLzEpg7sTI',
    appId: '1:658701940288:web:f65ec3b50c651f188c11a5',
    messagingSenderId: '658701940288',
    projectId: 'unieventosapp',
    authDomain: 'unieventosapp.firebaseapp.com',
    storageBucket: 'unieventosapp.firebasestorage.app',
    measurementId: 'G-GQEM0DRCSK',
  );

}